### ISSUE TITLE
Deletion infrastructure

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/librarian#24]
We need to set up some kind of infrastructure to allow us to safely delete certain data files. Exact implementation to depend a lot on the policy that we decide we want to deploy on the Karoo.

**Comment by pkgw** [comment]
Here are some thoughts I have — I first wrote them in a private email to @dannyjacobs but I realized that it would be helpful to enshrine them in the historical record by copyting them here too.

I feel like the only bit that takes careful thought is the safety infrastructure that helps us be confident that a malformed command isn't going to delete half of the archive. Other stuff is just wiring up an API call, exposing it in a command-line program, etc.

The main idea I had for safety was to add a boolean flag to each "file instance" called "deletable". You're not allowed to delete an instance unless it's true. Straightforward enough.

Then, raw data from the correlator get ingested with deletable=true, but RTP files don't, and of course the default is "false".

Purging data is a matter of a cronjob that deletes files matching a query like

```
ORIGIN = "correlator" && NAME like (whatever) && AGE > 4 days && [derived RTP output files exist]
```

(The requirement that deletable=true would be enforced at a lower level.)

The above query may require some extension of the search framework, but I definitely like the idea of implementing this query within that framework. If the query is implemented correctly the "deleteable" flag should never come into play but, again, it adds some safety in case someone makes a typo so that the query matches every file, or whatever.

Another idea that I had was that the API call to "delete files matching this query: <....>" also take arguments specifying information along the lines of "the query should match between N and M files, totaling size between X and Y" or something like that. In normal operations, the query will always match about the same amount of data, but in case something goes wonky and suddenly the query matches way more files than expected, it refuses to run.

But, I think I would be happy with just the "deletable" flag.

**Comment by miguelfmorales** [comment]
I like this.

One question, what is your opinion of a pattern where the correlator files are marked not-deletable when written by the correlator, but after running through the RTP it marks them as deletable? This would be more like a primitive garbage collection pattern where programs can say, I'm okay with this being deleted.

I also like the counting idea. Maybe even at the level of an optional (but recommended) value that the delete should fail if the query returns more than X files. Doesn't hamstring things too much, but makes it really easy to provide sanity checks when writing the code.

M

On Dec 1, 2016, at 8:26 AM, Peter Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are some thoughts I have — I first wrote them in a private email to @dannyjacobs<https://github.com/dannyjacobs> but I realized that it would be helpful to enshrine them in the historical record by copyting them here too.

I feel like the only bit that takes careful thought is the safety infrastructure that helps us be confident that a malformed command isn't going to delete half of the archive. Other stuff is just wiring up an API call, exposing it in a command-line program, etc.

The main idea I had for safety was to add a boolean flag to each "file instance" called "deletable". You're not allowed to delete an instance unless it's true. Straightforward enough.

Then, raw data from the correlator get ingested with deletable=true, but RTP files don't, and of course the default is "false".

Purging data is a matter of a cronjob that deletes files matching a query like

ORIGIN = "correlator" && NAME like (whatever) && AGE > 4 days && [derived RTP output files exist]


(The requirement that deletable=true would be enforced at a lower level.)

The above query may require some extension of the search framework, but I definitely like the idea of implementing this query within that framework. If the query is implemented correctly the "deleteable" flag should never come into play but, again, it adds some safety in case someone makes a typo so that the query matches every file, or whatever.

Another idea that I had was that the API call to "delete files matching this query: <....>" also take arguments specifying information along the lines of "the query should match between N and M files, totaling size between X and Y" or something like that. In normal operations, the query will always match about the same amount of data, but in case something goes wonky and suddenly the query matches way more files than expected, it refuses to run.

But, I think I would be happy with just the "deletable" flag.

**Comment by dannyjacobs** [comment]
I like that its a two part process.  The submitter marks it as deletable and but the deletion only goes after RTP has finished and returned the correct products.  You could imagine the "deletable" actually being more of a reference to a "deletion policy".


In my mind, a deletable flag is a backstop against deleting the rest of the inventory; since only new files which are marked from the beginning as "deleteable" can be deleted and old files will be marked "not deletable" by default. I think of it more like allowing the observer some control over the mode in which they are operating.

We could consider making it part of the correlator API, so that the observer sets the deletable flag.

**Comment by pkgw** [comment]
This has been implemented in the series of commits culminating in 6ac10ac.
